# Generated by Django 5.1.2 on 2024-11-08 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='prodapp',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ML', 'CAFE'), ('CR', 'PANELA'), ('LS', 'AGUACATE'), ('MS', 'PLATANO'), ('PN', 'CAÑA'), ('GH', 'PAPA'), ('CZ', 'VIVO'), ('IC', 'HONOR')], max_length=2),
        ),
    ]
